In [2]:
import numpy as np
a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([1.0, 2.0, 3.0])
a[:, np.newaxis]+b
#1*4  1*3 = 4*3 --> 

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [3]:
a[:, np.newaxis]

array([[ 0.],
       [10.],
       [20.],
       [30.]])

In [4]:
a

array([ 0., 10., 20., 30.])

In [ ]:
from numpy import array, argmin, sqrt, sum
observation = array([111.0, 188.0])
codes = 

In [6]:
# load library
import pandas as pd

# create url
url = "https://raw.githubusercontent.com/chrisalbon/sim_data/master/data.json"

# load data
df = pd.read_json(url, orient="columns")

# view first two rows
df.head(2)

integer            datetime  category
0        5 2015-01-01 00:00:00         0
1        5 2015-01-01 00:00:01         0

In [28]:
!pip install pyarrow

  Obtaining dependency information for pyarrow from https://files.pythonhosted.org/packages/54/e3/d5cfd7654084e6c0d9c3ce949e5d9e0ccad569ae1e2d5a68a3ec03b2be89/pyarrow-19.0.1-cp310-cp310-win_amd64.whl.metadata
   ---------------------------------------- 0.0/25.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/25.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/25.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/25.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/25.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/25.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/25.3 MB 81.9 kB/s eta 0:05:09
   ---------------------------------------- 0.1/25.3 MB 172.4 kB/s eta 0:02:27
   ---------------------------------------- 0.1/25.3 MB 208.4 kB/s eta 0:02:01
   ---------------------------------------- 0.1/25.3 MB 208.4 kB/s eta 0:02:01
   ---------------------------------------- 0.1/25.3 MB 


[notice] A new release of pip is available: 23.1.2 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


   ----------- ---------------------------- 7.5/25.3 MB 210.3 kB/s eta 0:01:25
   ----------- ---------------------------- 7.5/25.3 MB 210.3 kB/s eta 0:01:25
   ----------- ---------------------------- 7.6/25.3 MB 210.5 kB/s eta 0:01:25
   ------------ --------------------------- 7.6/25.3 MB 210.9 kB/s eta 0:01:24
   ------------ --------------------------- 7.6/25.3 MB 210.9 kB/s eta 0:01:24
   ------------ --------------------------- 7.6/25.3 MB 212.0 kB/s eta 0:01:24
   ------------ --------------------------- 7.6/25.3 MB 212.0 kB/s eta 0:01:24
   ------------ --------------------------- 7.6/25.3 MB 212.0 kB/s eta 0:01:24
   ------------ --------------------------- 7.6/25.3 MB 212.0 kB/s eta 0:01:24
   ------------ --------------------------- 7.6/25.3 MB 211.8 kB/s eta 0:01:24
   ------------ --------------------------- 7.7/25.3 MB 212.0 kB/s eta 0:01:24
   ------------ --------------------------- 7.7/25.3 MB 213.6 kB/s eta 0:01:23
   ------------ --------------------------- 7.7/25.3

In [29]:
# Load library
import pandas as pd
# Create URL
url = 'https://machine-learning-python-cookbook.s3.amazonaws.com/data.parquet'
# Load data
dataframe = pd.read_parquet(url)
# View the first two rows
dataframe.head(2)

integer             datetime  category
0        5  2015-01-01 00:00:00         0
1        5  2015-01-01 00:00:01         0

In [26]:
!pip install pandavro

  Obtaining dependency information for pandavro from https://files.pythonhosted.org/packages/3b/74/13b8900ee2c617e5c782b1f2524122addf508030abe28cbe9106e3540110/pandavro-1.8.0-py3-none-any.whl.metadata
  Obtaining dependency information for fastavro<2.0.0,>=1.5.1 from https://files.pythonhosted.org/packages/6a/1d/7a54fac3f90f0dc120b92f244067976831e393789d3b78c08f2b035ccb19/fastavro-1.10.0-cp310-cp310-win_amd64.whl.metadata
   ---------------------------------------- 0.0/497.3 kB ? eta -:--:--
   - ------------------------------------- 20.5/497.3 kB 217.9 kB/s eta 0:00:03
   - ------------------------------------- 20.5/497.3 kB 217.9 kB/s eta 0:00:03
   - ------------------------------------- 20.5/497.3 kB 217.9 kB/s eta 0:00:03
   - ------------------------------------- 20.5/497.3 kB 217.9 kB/s eta 0:00:03
   - ------------------------------------- 20.5/497.3 kB 217.9 kB/s eta 0:00:03
   -- ------------------------------------- 30.7/497.3 kB 81.9 kB/s eta 0:00:06
   --- ----------------


[notice] A new release of pip is available: 23.1.2 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [27]:
# Load library
import requests
import pandavro as pdx
# Create URL
url = 'https://machine-learning-python-cookbook.s3.amazonaws.com/data.avro'
# Download file
r = requests.get(url)
open('data.avro', 'wb').write(r.content)
# Load data
dataframe = pdx.read_avro('data.avro')
# View the first two rows
dataframe.head(2)

integer             datetime  category
0        5  2015-01-01 00:00:00         0
1        5  2015-01-01 00:00:01         0

In [30]:
!pip install sqlalchemy

  Obtaining dependency information for sqlalchemy from https://files.pythonhosted.org/packages/20/a8/08f6ceccff5e0abb4a22e2e91c44b0e39911fda06b5d0c905dfc642de57a/SQLAlchemy-2.0.38-cp310-cp310-win_amd64.whl.metadata
  Obtaining dependency information for greenlet!=0.4.17 from https://files.pythonhosted.org/packages/96/28/d62835fb33fb5652f2e98d34c44ad1a0feacc8b1d3f1aecab035f51f267d/greenlet-3.1.1-cp310-cp310-win_amd64.whl.metadata
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
    --------------------------------------- 0.0/2.1 MB 660.6 kB/s eta 0:00:04
    --------------------------------------- 0.0/2.1 MB 495.5 kB/s eta 0:00:05
    --------------------------------------- 0.0/2.1 MB 495.5 kB/s eta 0:00:05
    --------------------------------------- 0.0/2.1 MB 495.5 kB/s eta 0:00:05
    --------------------------------------- 0.0/2.1 MB 495.5 kB/s eta 0:00:05
   - -------------------------------------- 0.1/2.1 MB 193.2 kB/s eta 0:00:11
   - -------------------------


[notice] A new release of pip is available: 23.1.2 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [31]:
# Load libraries
import pandas as pd
from sqlalchemy import create_engine
# Create a connection to the database
database_connection = create_engine('sqlite:///sample.db')
# Load data
dataframe = pd.read_sql_query('SELECT * FROM data', database_connection)
# View first two rows
dataframe.head(2)

OperationalError: (sqlite3.OperationalError) no such table: data
[SQL: SELECT * FROM data]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [33]:
!pip install pymysql

  Obtaining dependency information for pymysql from https://files.pythonhosted.org/packages/0c/94/e4181a1f6286f545507528c78016e00065ea913276888db2262507693ce5/PyMySQL-1.1.1-py3-none-any.whl.metadata
   ---------------------------------------- 0.0/45.0 kB ? eta -:--:--
   ------------------ --------------------- 20.5/45.0 kB ? eta -:--:--
   ------------------ --------------------- 20.5/45.0 kB ? eta -:--:--
   ------------------ --------------------- 20.5/45.0 kB ? eta -:--:--
   ------------------ --------------------- 20.5/45.0 kB ? eta -:--:--
   ---------------------------------------- 45.0/45.0 kB 148.4 kB/s eta 0:00:00



[notice] A new release of pip is available: 23.1.2 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [38]:
# Import libraries
import pymysql
import pandas as pd

# Initialize conn to None
conn = None

try:
    # Create a DB connection
    conn = pymysql.connect(
        host='localhost',
        user='root',
        password="",  # اگر رمز عبور دارید، آن را اینجا وارد کنید
        db='db',     # نام دیتابیس را بررسی کنید
        port=3306    # پورت پیش‌فرض MySQL
    )
    
    # Read the SQL query into a dataframe
    dataframe = pd.read_sql("SELECT * FROM data", conn)
    
    # View the first two rows
    print(dataframe.head(2))

except pymysql.MySQLError as e:
    print(f"Error connecting to MySQL: {e}")
except Exception as e:
    print(f"An unexpected error occurred: {e}")
finally:
    # Close the connection if it was successfully created
    if conn:
        conn.close()

Error connecting to MySQL: (2003, "Can't connect to MySQL server on 'localhost' ([WinError 10061] No connection could be made because the target machine actively refused it)")


In [11]:
# Import libraries
import pandas as pd
# Google Sheet URL that downloads the sheet as a CSV
url = "https://docs.google.com/spreadsheets/d/"\
"1ehC-9otcAuitqnmWksqt1mOrTRCL38dv0K9UjhwzTOA/export?format=csv"
# Read the CSV into a dataframe
dataframe = pd.read_csv(url)
# View the first two rows
dataframe.head(2)

integer            datetime  category
0        5  2015-01-01 0:00:00         0
1        5  2015-01-01 0:00:01         0

In [16]:
# Import libraries
import requests
# URL to download the txt file from
txt_url = "https://machine-learning-python-cookbook.s3.amazonaws.com/text.txt"
# Get the txt file
r = requests.get(txt_url)
# Write it to text.txt locally
with open('text.txt', 'wb') as f:
     f.write(r.content)
# Read in the file
with open('text.txt', 'r') as f:
     text = f.read()
# Print the content
print(text)

Hello there!


In [17]:
# Load library
import pandas as pd
# Create URL
url = 'https://raw.githubusercontent.com/chrisalbon/sim_data/master/titanic.csv'
# Load data as a dataframe
dataframe = pd.read_csv(url)
# Show first five rows
dataframe.head(5)

Name PClass    Age     Sex  \
0                   Allen, Miss Elisabeth Walton    1st  29.00  female   
1                    Allison, Miss Helen Loraine    1st   2.00  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.00    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
4                  Allison, Master Hudson Trevor    1st   0.92    male   

   Survived  SexCode  
0         1        1  
1         0        1  
2         0        0  
3         0        1  
4         1        0

In [18]:
# Load library
import pandas as pd
# Create a dictionary
dictionary = {
    "Name": ['Jacky Jackson', 'Steven Stevenson'],
    "Age": [38, 25],
    "Driver": [True, False]
} 
#Create DataFrame
dataframe = pd.DataFrame(dictionary)
# Show DataFrame
dataframe

Name  Age  Driver
0     Jacky Jackson   38    True
1  Steven Stevenson   25   False

In [19]:
# Add a column for eye color
dataframe["Eyes"] = ["Brown", "Blue"]
# Show DataFrame
dataframe

Name  Age  Driver   Eyes
0     Jacky Jackson   38    True  Brown
1  Steven Stevenson   25   False   Blue

In [20]:
# Load library
import pandas as pd
# Create URL
url = 'https://raw.githubusercontent.com/chrisalbon/sim_data/master/titanic.csv'
# Load data
dataframe = pd.read_csv(url)
# Show two rows
dataframe.head(2)

Name PClass   Age     Sex  Survived  SexCode
0  Allen, Miss Elisabeth Walton    1st  29.0  female         1        1
1   Allison, Miss Helen Loraine    1st   2.0  female         0        1

In [21]:
# Show dimensions
dataframe.shape

(1313, 6)

In [22]:
# Show statistics
dataframe.describe()

Age     Survived      SexCode
count  756.000000  1313.000000  1313.000000
mean    30.397989     0.342727     0.351866
std     14.259049     0.474802     0.477734
min      0.170000     0.000000     0.000000
25%     21.000000     0.000000     0.000000
50%     28.000000     0.000000     0.000000
75%     39.000000     1.000000     1.000000
max     71.000000     1.000000     1.000000

In [23]:
# Show info
dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1313 entries, 0 to 1312
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Name      1313 non-null   object 
 1   PClass    1313 non-null   object 
 2   Age       756 non-null    float64
 3   Sex       1313 non-null   object 
 4   Survived  1313 non-null   int64  
 5   SexCode   1313 non-null   int64  
dtypes: float64(1), int64(2), object(3)
memory usage: 61.7+ KB
