In [6]:
# Load library
import numpy as np
# Create a vector as a row
vector_row = np.array([1, 2, 3])
# Create a vector as a column
vector_column = np.array([[1],
                          [2],
                          [3]])
print(vector_column)

[[1]
 [2]
 [3]]


In [7]:
# Load library
import numpy as np
# Create a matrix
matrix = np.array([[1, 2],
                   [1, 2],
                   [1, 2]])
print(matrix)

[[1 2]
 [1 2]
 [1 2]]


In [8]:
matrix_object = np.mat([[1, 2],
                        [1, 2],
                        [1, 2]])
print(matrix_object)

[[1 2]
 [1 2]
 [1 2]]


In [10]:
# Load libraries
import numpy as np
from scipy import sparse
# Create a matrix
matrix = np.array([[0, 0],
                   [0, 1],
                   [3, 0]])
# Create compressed sparse row (CSR) matrix
matrix_sparse = sparse.csr_matrix(matrix)
# View sparse matrix
print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


In [12]:
# Create larger matrix
matrix_large = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                         [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
                         [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]])
# Create compressed sparse row (CSR) matrix
matrix_large_sparse = sparse.csr_matrix(matrix_large)
# View original sparse matrix
print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


In [13]:
# View larger sparse matrix
print(matrix_large_sparse)

  (1, 1)	1
  (2, 0)	3


In [15]:
# Load library
import numpy as np
# Generate a vector of shape (1,5) containing all zeros
vector = np.zeros(shape=5)
# View the matrix
print(vector)

[0. 0. 0. 0. 0.]


In [16]:
# Generate a matrix of shape (3,3) containing all ones
matrix = np.full(shape=(3,3), fill_value=1)
# View the vector
print(matrix)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [17]:
# Load library
import numpy as np
# Create row vector
vector = np.array([1, 2, 3, 4, 5, 6])
# Create matrix
matrix = np.array([[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
# Select third element of vector
vector[2]

3

In [18]:
#Select second row, second column
matrix[1,1]

5

In [20]:
# Select all elements of a vector
vector[:]

array([1, 2, 3, 4, 5, 6])

In [21]:
# Select everything up to and including the third element
vector[:3]

array([1, 2, 3])

In [22]:
# Select everything after the third element
vector[3:]

array([4, 5, 6])

In [23]:
# Select the last element
vector[-1]

6

In [24]:
#Reverse the vector
vector[::-1]

array([6, 5, 4, 3, 2, 1])

In [25]:
# Select the first two rows and all columns of a matrix
matrix[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
# Select all rows and the second column
matrix[:,1:2]

array([[2],
       [5],
       [8]])

In [27]:
# Load library
import numpy as np
# Create matrix
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])
# View number of rows and columns
matrix.shape

(3, 4)

In [28]:
# View number of elements (rows * columns)
matrix.size

12

In [29]:
# View number of dimensions
matrix.ndim

2

In [30]:
# Load library
import numpy as np
# Create matrix
matrix = np.array([[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
# Create function that adds 100 to something
add_100 = lambda i: i + 100
# Create vectorized function
vectorized_add_100 = np.vectorize(add_100)
# Apply function to all elements in matrix
vectorized_add_100(matrix)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [31]:
# Add 100 to all elements
matrix + 100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [32]:
# Load library
import numpy as np
# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
# Return maximum element
np.max(matrix)

9

In [33]:
#Return minimum element
np.min(matrix)

1

In [34]:
# Find maximum element in each column
np.max(matrix, axis=0)

array([7, 8, 9])

In [35]:
# Find maximum element in each row
np.max(matrix, axis=1)

array([3, 6, 9])

In [36]:
# Load library
import numpy as np
# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
# Return mean
np.mean(matrix)

5.0

In [37]:
# Return variance
np.var(matrix)

6.666666666666667

In [38]:
# Return standard deviation
np.std(matrix)

2.581988897471611

In [39]:
# Find the mean value in each column
np.mean(matrix, axis=0)

array([4., 5., 6.])

In [40]:
# Load library
import numpy as np
# Create 4x3 matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [10, 11, 12]])
# Reshape matrix into 2x6 matrix
matrix.reshape(2, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [41]:
matrix.size

12

In [42]:
matrix.reshape(1, -1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [43]:
matrix.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [44]:
# Load library
import numpy as np
# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
# Transpose matrix
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [45]:
# Transpose vector
np.array([1, 2, 3, 4, 5, 6]).T

array([1, 2, 3, 4, 5, 6])

In [46]:
# Transpose row vector
np.array([[1, 2, 3, 4, 5, 6]]).T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [47]:
# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
# Flatten matrix
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
matrix.reshape(1, -1)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [49]:
# Create one matrix
matrix_a = np.array([[1, 2],
                     [3, 4]])
# Create a second matrix
matrix_b = np.array([[5, 6],
                     [7, 8]])
# Create a list of matrices
matrix_list = [matrix_a, matrix_b]
# Flatten the entire list of matrices
np.ravel(matrix_list)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [50]:
# Create matrix
matrix = np.array([[1, 1, 1],
                   [1, 1, 10],
                   [1, 1, 15]])
# Return matrix rank
np.linalg.matrix_rank(matrix)

2

In [51]:
# Create matrix
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])
# Return diagonal elements
matrix.diagonal()

array([1, 4, 9])

In [52]:
# Return diagonal one above the main diagonal
matrix.diagonal(offset=1)

array([2, 6])

In [53]:
# Return diagonal one below the main diagonal
matrix.diagonal(offset=-1)

array([2, 8])

In [54]:
# Create matrix
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])
# Return trace
matrix.trace()

14

In [55]:
# Return diagonal and sum elements
sum(matrix.diagonal())

14

In [56]:
# Load library
import numpy as np
# Create two vectors
vector_a = np.array([1,2,3])
vector_b = np.array([4,5,6])
# Calculate dot product
np.dot(vector_a, vector_b)

32

In [57]:
# Calculate dot product
vector_a @ vector_b

32

In [58]:
# Create matrix
matrix_a = np.array([[1, 1, 1],
                     [1, 1, 1],
                     [1, 1, 2]])
# Create matrix
matrix_b = np.array([[1, 3, 1],
                     [1, 3, 1],
                     [1, 3, 8]])
# Add two matrices
np.add(matrix_a, matrix_b)

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [59]:
# Subtract two matrices
np.subtract(matrix_a, matrix_b)

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

In [60]:
# Add two matrices
matrix_a + matrix_b

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [61]:
# Create matrix
matrix_a = np.array([[1, 1],
                     [1, 2]])
# Create matrix
matrix_b = np.array([[1, 3],
                     [1, 2]])
# Multiply two matrices
np.dot(matrix_a, matrix_b)

array([[2, 5],
       [3, 7]])

In [62]:
# Multiply two matrices
matrix_a @ matrix_b

array([[2, 5],
       [3, 7]])

In [63]:
# Multiply two matrices element-wise
matrix_a * matrix_b

array([[1, 3],
       [1, 4]])

In [64]:
# Create matrix
matrix = np.array([[1, 4],
                   [2, 5]])
# Calculate inverse of matrix
np.linalg.inv(matrix)

array([[-1.66666667,  1.33333333],
       [ 0.66666667, -0.33333333]])

In [65]:
# Multiply matrix and its inverse
matrix @ np.linalg.inv(matrix)

array([[1., 0.],
       [0., 1.]])

In [66]:
# Set seed
np.random.seed(0)
# Generate three random floats between 0.0 and 1.0
np.random.random(3)

array([0.5488135 , 0.71518937, 0.60276338])

In [67]:
# Generate three random integers between 0 and 10
np.random.randint(0, 11, 3)

array([3, 7, 9])

In [68]:
# Draw three numbers from a normal distribution with mean 0.0
# and standard deviation of 1.0
np.random.normal(0.0, 1.0, 3)

array([-1.42232584,  1.52006949, -0.29139398])

In [69]:
# Draw three numbers from a logistic distribution with mean 0.0 and scale of 1.0
np.random.logistic(0.0, 1.0, 3)

array([-0.98118713, -0.08939902,  1.46416405])

In [70]:
# Draw three numbers greater than or equal to 1.0 and less than 2.0
np.random.uniform(1.0, 2.0, 3)

array([1.47997717, 1.3927848 , 1.83607876])