In [2]:
import tensorflow as tf

In [ ]:
tensor_zero_d= tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
tensor_one_d= tf.constant([0.,2,-3,8,90], dtype = tf.float32)
print(tensor_one_d)

tf.Tensor([ 0.  2. -3.  8. 90.], shape=(5,), dtype=float32)


In [ ]:
tensor_one_d= tf.constant([0,2,-3,8,90])
print(tensor_one_d)

tf.Tensor([ 0  2 -3  8 90], shape=(5,), dtype=int32)


In [ ]:
tensor_one_d= tf.constant([0,2,-3,8,90], dtype = tf.float32)
print(tensor_one_d)

tf.Tensor([ 0.  2. -3.  8. 90.], shape=(5,), dtype=float32)


In [ ]:
tensor_one_d= tf.constant([0,2,-3,8,90.])
print(tensor_one_d)

tf.Tensor([ 0.  2. -3.  8. 90.], shape=(5,), dtype=float32)


In [ ]:
tensor_one_d= tf.constant([0.,2,-3,8,90], dtype = tf.float32)
casted_tensor_one_d=tf.cast(tensor_one_d, dtype=tf.int16)
casted_tensor_one_2_d=tf.cast(tensor_one_d, dtype=tf.bool)
print(tensor_one_d)
print(casted_tensor_one_d)
print(casted_tensor_one_2_d)

tf.Tensor([ 0.  2. -3.  8. 90.], shape=(5,), dtype=float32)
tf.Tensor([ 0  2 -3  8 90], shape=(5,), dtype=int16)
tf.Tensor([False  True  True  True  True], shape=(5,), dtype=bool)


In [ ]:
tensor_bool= tf.constant([True, True, False])
print(tensor_bool)

tf.Tensor([ True  True False], shape=(3,), dtype=bool)


In [ ]:
tensor_string= tf.constant("Hello World!")
print(tensor_string)

tf.Tensor(b'Hello World!', shape=(), dtype=string)


In [ ]:
tensor_string= tf.constant(["Hello World!", "hi"])
print(tensor_string)

tf.Tensor([b'Hello World!' b'hi'], shape=(2,), dtype=string)


In [ ]:
tensor_two_d= tf.constant([
    [1, 2, 0],
    [3, 5, -1],
    [1, 5, 6],
    [2, 3, 8],
])
print(tensor_two_d)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


In [ ]:
tensor_three_d= tf.constant(
[[[1, 2, 0],
 [3, 5, -1]],

[[10, 2, 0],
 [1, 0, 2]],

[[5, 8, 0],
 [2, 7, 0]],

[[2, 1, 9],
 [4, -3, 32]],
])
print(tensor_three_d)

tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[10  2  0]
  [ 1  0  2]]

 [[ 5  8  0]
  [ 2  7  0]]

 [[ 2  1  9]
  [ 4 -3 32]]], shape=(4, 2, 3), dtype=int32)


In [ ]:
print(tensor_three_d.shape)
print(tensor_two_d.shape)
print(tensor_one_d.shape)
print(tensor_zero_d.shape)

(4, 2, 3)
(4, 3)
(5,)
()


In [ ]:
print(tensor_three_d.ndim)

3


In [ ]:
tensor_four_d= tf.constant([
    [
    [[1, 2, 0],
      [3, 5, -1]],

    [[10, 2, 0],
      [1, 0, 2]],

    [[5, 8, 0],
      [2, 7, 0]],

    [[2, 1, 9],
      [4, -3, 32]]
],

[
    [[13, 26, 0],
      [3, 5, -12]],

    [[10, 2, 0],
      [1, 0, 23]],

    [[5, 8, 0],
      [2, 73, 0]],

    [[2, 1, 9],
      [4, -30, 32]]
],

[
    [[103, 26, 0],
      [3, 50, -12]],

   [[100, 2, 0],
      [1, 0, 23]],

   [[5, 28, 0],
      [2, 3, 0]],

   [[22, 1, 9],
      [44, -320, 32]]
],
])
print(tensor_four_d)

tf.Tensor(
[[[[   1    2    0]
   [   3    5   -1]]

  [[  10    2    0]
   [   1    0    2]]

  [[   5    8    0]
   [   2    7    0]]

  [[   2    1    9]
   [   4   -3   32]]]


 [[[  13   26    0]
   [   3    5  -12]]

  [[  10    2    0]
   [   1    0   23]]

  [[   5    8    0]
   [   2   73    0]]

  [[   2    1    9]
   [   4  -30   32]]]


 [[[ 103   26    0]
   [   3   50  -12]]

  [[ 100    2    0]
   [   1    0   23]]

  [[   5   28    0]
   [   2    3    0]]

  [[  22    1    9]
   [  44 -320   32]]]], shape=(3, 4, 2, 3), dtype=int32)


In [ ]:
import numpy as np

In [ ]:
np_array = np.array([1, 2, 4])
print(np_array)

[1 2 4]


In [ ]:
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 4], shape=(3,), dtype=int64)


In [ ]:
eye_tensor = tf.eye(
    num_rows=3,
    num_columns=None,
    batch_shape = None,
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [ ]:
eye_tensor = tf.eye(
    num_rows=3,
    num_columns=None,
    batch_shape = None,
    dtype=tf.dtypes.float16,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float16)


In [ ]:
eye_tensor = tf.eye(
    num_rows=3,
    num_columns=None,
    batch_shape = None,
    dtype=tf.dtypes.bool,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[ True False False]
 [False  True False]
 [False False  True]], shape=(3, 3), dtype=bool)


In [ ]:
eye_tensor = tf.eye(
    num_rows=5,
    num_columns=3,
    batch_shape = None,
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(5, 3), dtype=float32)


In [ ]:
eye_tensor = tf.eye(
    num_rows=5,
    num_columns=None,
    batch_shape = [3,],
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]

 [[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]

 [[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]], shape=(3, 5, 5), dtype=float32)


In [ ]:
eye_tensor = tf.eye(
    num_rows=5,
    num_columns=None,
    batch_shape = [2,],
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]

 [[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]], shape=(2, 5, 5), dtype=float32)


In [ ]:
eye_tensor = tf.eye(
    num_rows=5,
    num_columns=None,
    batch_shape = [2,4],
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]]


 [[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]]], shape=(2, 4, 5, 5), dtype=float32)


In [ ]:
fill_tensor=tf.fill(
    [3, 4], 5, name=None
)
print(fill_tensor)

tf.Tensor(
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]], shape=(3, 4), dtype=int32)


In [ ]:
fill_tensor=tf.fill(
    [1, 3, 4], 5, name=None
)
print(fill_tensor)

tf.Tensor(
[[[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]], shape=(1, 3, 4), dtype=int32)


In [ ]:
ones_tensor=tf.ones(
    [5, 3],
    dtype = tf.dtypes.float32,
    name=None
)
print(ones_tensor)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(5, 3), dtype=float32)


In [ ]:
ones_tensor=tf.ones(
    [5, 3, 2],
    dtype = tf.dtypes.float32,
    name=None
)
print(ones_tensor)

tf.Tensor(
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]], shape=(5, 3, 2), dtype=float32)


In [ ]:
ones_like_tensor= tf.ones_like(fill_tensor)
print(ones_like_tensor)

tf.Tensor(
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]], shape=(1, 3, 4), dtype=int32)


In [ ]:
zeros_tensor=tf.zeros(
    [3, 2],
    dtype = tf.dtypes.float32,
    name=None
)
print(zeros_tensor)

tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)


In [ ]:
zeros_like_tensor= tf.zeros_like(fill_tensor)
print(zeros_like_tensor)

tf.Tensor(
[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]], shape=(1, 3, 4), dtype=int32)


In [ ]:
print(tf.shape(tensor_three_d))

tf.Tensor([4 2 3], shape=(3,), dtype=int32)


In [ ]:
#shape of tensor "t" is [2, 2, 3]
t = tf.constant([[[1, 1, 1],[2, 2, 2]], [[3, 3, 3], [4, 4, 4]]])
tf.rank(t)   #3

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [ ]:
#shape of tensor "t" is [2, 2, 3]
t = tf.constant([[1, 1, 1],[2, 2, 2]])
tf.rank(t)   #2

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [ ]:
t = tf.constant([[[1, 1, 1],[2, 2, 2]], [[3, 3, 3], [4, 4, 4]]])
tf.size(t)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [ ]:
t = tf.constant([[1, 1, 1],[2, 2, 2]],)
tf.size(t)

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [ ]:
t = tf.constant([[1, 1, 1],[2, 2, 2]],)
tf.size(t, out_type= tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

In [ ]:
random_tensor = tf.random.normal(
    [3, 2],
    mean=0.0,
    stddev=1.0,
    dtype = tf.dtypes.float32,
    seed = None,
    name = None
)
print(random_tensor)

tf.Tensor(
[[-0.79735166 -0.06911026]
 [ 1.9580196   2.2068725 ]
 [-1.57225    -0.6802045 ]], shape=(3, 2), dtype=float32)


In [ ]:
random_tensor = tf.random.normal(
    [3, 2],
    mean=100.0,
    stddev=1.0,
    dtype = tf.dtypes.float32,
    seed = None,
    name = None
)
print(random_tensor)

tf.Tensor(
[[ 99.14281  100.16724 ]
 [100.7768   100.39339 ]
 [100.956154  99.813324]], shape=(3, 2), dtype=float32)


In [ ]:
#******************************************************************

In [ ]:
random_tensor = tf.random.uniform(
    [1,],
    minval=0,
    maxval=None,
    dtype = tf.dtypes.float32,
    seed = None,
    name = None
)
print(random_tensor)

tf.Tensor([0.65420914], shape=(1,), dtype=float32)


In [ ]:
random_tensor = tf.random.uniform(
    [5,],
    minval=0,
    maxval=None,
    dtype = tf.dtypes.float32,
    seed = None,
    name = None
)
print(random_tensor)

tf.Tensor([0.9576224  0.11179256 0.7101289  0.9860616  0.0040077 ], shape=(5,), dtype=float32)


In [ ]:
random_tensor = tf.random.uniform(
    [5,],
    minval=0,
    maxval=8,
    dtype = tf.dtypes.float32,
    seed = None,
    name = None
)
print(random_tensor)

tf.Tensor([7.76073    6.3235664  4.5521536  0.00842476 5.1320686 ], shape=(5,), dtype=float32)


In [ ]:
random_tensor = tf.random.uniform(
    [5,],
    minval=0,
    maxval=100,
    dtype = tf.dtypes.float32,
    seed = None,
    name = None
)
print(random_tensor)

tf.Tensor([77.07161   81.161224   3.7303567 38.735546  55.350555 ], shape=(5,), dtype=float32)


In [ ]:
random_tensor = tf.random.uniform(
    [5,],
    minval=0,
    maxval=1000,
    dtype = tf.dtypes.int32,
    seed = None,
    name = None
)
print(random_tensor)

tf.Tensor([479 423 212 912  89], shape=(5,), dtype=int32)


In [ ]:
random_tensor = tf.random.uniform(
    [5,5],
    minval=0,
    maxval=1000,
    dtype = tf.dtypes.int32,
    seed = None,
    name = None
)
print(random_tensor)

tf.Tensor(
[[422  92 851  17 252]
 [ 58 110 476  36 509]
 [775 291 626 570 415]
 [243 620 182 428 690]
 [ 26  87 113 394 997]], shape=(5, 5), dtype=int32)


In [ ]:
tf.random.set_seed(5)
print(tf.random.uniform(shape=[3,], maxval=5, dtype = tf.dtypes.int32, seed = 10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype = tf.dtypes.int32, seed = 10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype = tf.dtypes.int32, seed = 10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype = tf.dtypes.int32, seed = 10))

tf.Tensor([4 3 1], shape=(3,), dtype=int32)
tf.Tensor([4 3 2], shape=(3,), dtype=int32)
tf.Tensor([1 1 1], shape=(3,), dtype=int32)
tf.Tensor([1 3 3], shape=(3,), dtype=int32)


In [ ]:
tf.random.set_seed(5)
print(tf.random.uniform(shape=[3,], maxval=5, dtype = tf.dtypes.int32, seed = 10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype = tf.dtypes.int32, seed = 10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype = tf.dtypes.int32, seed = 10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype = tf.dtypes.int32, seed = 10))

tf.Tensor([4 3 1], shape=(3,), dtype=int32)
tf.Tensor([4 3 2], shape=(3,), dtype=int32)
tf.Tensor([1 1 1], shape=(3,), dtype=int32)
tf.Tensor([1 3 3], shape=(3,), dtype=int32)


In [ ]:
tf.random.set_seed(5)
print(tf.random.uniform(shape=[3,], maxval=5, dtype = tf.dtypes.int32, seed = 10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype = tf.dtypes.int32, seed = 10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype = tf.dtypes.int32, seed = 10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype = tf.dtypes.int32, seed = 1))

tf.Tensor([4 3 1], shape=(3,), dtype=int32)
tf.Tensor([4 3 2], shape=(3,), dtype=int32)
tf.Tensor([1 1 1], shape=(3,), dtype=int32)
tf.Tensor([4 1 3], shape=(3,), dtype=int32)


In [ ]:
print(tf.random.uniform(shape=[3,], maxval=5, dtype = tf.dtypes.int32, seed = 10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype = tf.dtypes.int32, seed = 10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype = tf.dtypes.int32, seed = 10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype = tf.dtypes.int32, seed = 10))

tf.Tensor([4 2 2], shape=(3,), dtype=int32)
tf.Tensor([4 2 1], shape=(3,), dtype=int32)
tf.Tensor([4 1 0], shape=(3,), dtype=int32)
tf.Tensor([1 2 1], shape=(3,), dtype=int32)


In [ ]:
tensor_indexed = tf.constant([3, 6, 2, 4, 6, 66, 7])
print(tensor_indexed)
print(tensor_indexed[:])
print(tensor_indexed[0:4])
print(tensor_indexed[:4])
print(tensor_indexed[3:])
print(tensor_indexed[3:-1])
print(tensor_indexed[3:-3])
print(tensor_indexed[3:-4])
print(tensor_indexed[0:5])
print(tensor_indexed[0:5+1])
print(tensor_indexed[0:6])
print(tensor_indexed[0:6:2])

tf.Tensor([ 3  6  2  4  6 66  7], shape=(7,), dtype=int32)
tf.Tensor([ 3  6  2  4  6 66  7], shape=(7,), dtype=int32)
tf.Tensor([3 6 2 4], shape=(4,), dtype=int32)
tf.Tensor([3 6 2 4], shape=(4,), dtype=int32)
tf.Tensor([ 4  6 66  7], shape=(4,), dtype=int32)
tf.Tensor([ 4  6 66], shape=(3,), dtype=int32)
tf.Tensor([4], shape=(1,), dtype=int32)
tf.Tensor([], shape=(0,), dtype=int32)
tf.Tensor([3 6 2 4 6], shape=(5,), dtype=int32)
tf.Tensor([ 3  6  2  4  6 66], shape=(6,), dtype=int32)
tf.Tensor([ 3  6  2  4  6 66], shape=(6,), dtype=int32)
tf.Tensor([3 2 6], shape=(3,), dtype=int32)


In [ ]:
tf.range(2,6)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([2, 3, 4, 5], dtype=int32)>

In [ ]:
tensor_two_d= tf.constant([
    [1, 2, 0],
    [3, 5, -1],
    [1, 5, 6],
    [2, 3, 8],
])
print(tensor_two_d[0:3,0:2])
print("*********************************************************")
print(tensor_two_d[0:3,:])
print("*********************************************************")
print(tensor_two_d[2,:])
print("*********************************************************")
print(tensor_two_d[2,0])
print("*********************************************************")
print(tensor_two_d[2,1:])
print("*********************************************************")
print(tensor_two_d[:,0])
print("*********************************************************")
print(tensor_two_d[1:3,0])
print("*********************************************************")
print(tensor_two_d[:,1])
print("*********************************************************")
print(tensor_two_d[...,1])

tf.Tensor(
[[1 2]
 [3 5]
 [1 5]], shape=(3, 2), dtype=int32)
*********************************************************
tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]], shape=(3, 3), dtype=int32)
*********************************************************
tf.Tensor([1 5 6], shape=(3,), dtype=int32)
*********************************************************
tf.Tensor(1, shape=(), dtype=int32)
*********************************************************
tf.Tensor([5 6], shape=(2,), dtype=int32)
*********************************************************
tf.Tensor([1 3 1 2], shape=(4,), dtype=int32)
*********************************************************
tf.Tensor([3 1], shape=(2,), dtype=int32)
*********************************************************
tf.Tensor([2 5 5 3], shape=(4,), dtype=int32)
*********************************************************
tf.Tensor([2 5 5 3], shape=(4,), dtype=int32)


In [6]:
tensor_three_d= tf.constant(
                             [[[1, 2, 0],
                             [3, 5, -1]],

                             [[10, 2, 0],
                               [1, 0, 2]],

                            [[5, 8, 0],
                              [2, 7, 0]],

                            [[2, 1, 9],
                             [4, -3, 32]],
])
print(tensor_three_d[ 0, :, :])
print("*********************************************************")
print(tensor_three_d[ 0, 0, :])
print("*********************************************************")
print(tensor_three_d[ 0, :, -1])
print("*********************************************************")
print(tensor_three_d[ 0, :, 2])
print("*********************************************************")
print(tensor_three_d[ 0:2, :, 2])
print("*********************************************************")
print(tensor_three_d[ 0:2, ..., 2])
print("*********************************************************")
print(tensor_three_d[ ..., :, 2])

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]], shape=(2, 3), dtype=int32)
*********************************************************
tf.Tensor([1 2 0], shape=(3,), dtype=int32)
*********************************************************
tf.Tensor([ 0 -1], shape=(2,), dtype=int32)
*********************************************************
tf.Tensor([ 0 -1], shape=(2,), dtype=int32)
*********************************************************
tf.Tensor(
[[ 0 -1]
 [ 0  2]], shape=(2, 2), dtype=int32)
*********************************************************
tf.Tensor(
[[ 0 -1]
 [ 0  2]], shape=(2, 2), dtype=int32)
*********************************************************
tf.Tensor(
[[ 0 -1]
 [ 0  2]
 [ 0  0]
 [ 9 32]], shape=(4, 2), dtype=int32)


In [7]:
x_abs = tf.constant([-2.25, 3.25])
tf.abs(x_abs)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2.25, 3.25], dtype=float32)>

In [9]:
tf.abs(tf.constant(0.2))

<tf.Tensor: shape=(), dtype=float32, numpy=0.20000000298023224>

In [10]:
tf.abs(tf.constant(-0.2))

<tf.Tensor: shape=(), dtype=float32, numpy=0.20000000298023224>

In [11]:
x_abs_complex = tf.constant([-2.25 + 4.75j])
tf.abs(x_abs_complex)

<tf.Tensor: shape=(1,), dtype=float64, numpy=array([5.25594901])>

In [12]:
tf.sqrt((-2.25)**2 + 4.75**2)

<tf.Tensor: shape=(), dtype=float32, numpy=5.255949020385742>

In [17]:
x_1 = tf.constant([5, 3, 6, 6, 4, 6], dtype = tf.int32)
x_2 = tf.constant([7, 6, 2, 6, 7, 11], dtype = tf.int32)
print(tf.add(x_1,x_2))
print(tf.multiply(x_1,x_2))
print(tf.subtract(x_1,x_2))
print(tf.divide(x_1,x_2))

tf.Tensor([12  9  8 12 11 17], shape=(6,), dtype=int32)
tf.Tensor([35 18 12 36 28 66], shape=(6,), dtype=int32)
tf.Tensor([-2 -3  4  0 -3 -5], shape=(6,), dtype=int32)
tf.Tensor([0.71428571 0.5        3.         1.         0.57142857 0.54545455], shape=(6,), dtype=float64)


In [20]:
x_1 = tf.constant([5, 3, 6, 6, 4, 6], dtype = tf.float32)
x_2 = tf.constant([7, 6, 2, 6, 0, 11], dtype = tf.float32)
print(tf.divide(x_1,x_2))
print(tf.math.divide_no_nan(x_1,x_2))

tf.Tensor([0.71428573 0.5        3.         1.                inf 0.54545456], shape=(6,), dtype=float32)
tf.Tensor([0.71428573 0.5        3.         1.         0.         0.54545456], shape=(6,), dtype=float32)


In [22]:
x_1 = tf.constant([5, 3, 6, 6, 4, 6], dtype = tf.float32)
x_2 = tf.constant([7], dtype = tf.float32)
x_2_streched = tf.constant([7, 7, 7, 7, 7, 7], dtype = tf.float32)
print(tf.add(x_1,x_2))
print(tf.add(x_1,x_2_streched))

tf.Tensor([12. 10. 13. 13. 11. 13.], shape=(6,), dtype=float32)
tf.Tensor([12. 10. 13. 13. 11. 13.], shape=(6,), dtype=float32)


In [24]:
x_1 = tf.constant([[5, 3, 6, 6, 4, 6], [5, 45, 65, 5, 53, 4]], dtype = tf.float32)
x_2 = tf.constant([7], dtype = tf.float32)
x_2_streched = tf.constant([7, 7, 7, 7, 7, 7], dtype = tf.float32)
print(tf.add(x_1,x_2))
print(tf.add(x_1,x_2_streched))
print("*****************************************************************************")
print(tf.multiply(x_1,x_2))

tf.Tensor(
[[12. 10. 13. 13. 11. 13.]
 [12. 52. 72. 12. 60. 11.]], shape=(2, 6), dtype=float32)
tf.Tensor(
[[12. 10. 13. 13. 11. 13.]
 [12. 52. 72. 12. 60. 11.]], shape=(2, 6), dtype=float32)
*****************************************************************************
tf.Tensor(
[[ 35.  21.  42.  42.  28.  42.]
 [ 35. 315. 455.  35. 371.  28.]], shape=(2, 6), dtype=float32)


In [25]:
x_1 = tf.constant([[5, 3, 6, 6, 4, 6],], dtype = tf.float32)
x_2 = tf.constant([7], dtype = tf.float32)
x_2_streched = tf.constant([7, 7, 7, 7, 7, 7], dtype = tf.float32)
print(tf.add(x_1,x_2))
print(tf.add(x_1,x_2_streched))

tf.Tensor([[12. 10. 13. 13. 11. 13.]], shape=(1, 6), dtype=float32)
tf.Tensor([[12. 10. 13. 13. 11. 13.]], shape=(1, 6), dtype=float32)


In [26]:
x_1 = tf.constant([[5, 3, 6, 6, 4, 6],], dtype = tf.float32)
x_2 = tf.constant([[7], [5], [3]], dtype = tf.float32)
print(tf.add(x_1,x_2))
print(tf.add(x_1,x_2_streched))

tf.Tensor(
[[12. 10. 13. 13. 11. 13.]
 [10.  8. 11. 11.  9. 11.]
 [ 8.  6.  9.  9.  7.  9.]], shape=(3, 6), dtype=float32)
tf.Tensor([[12. 10. 13. 13. 11. 13.]], shape=(1, 6), dtype=float32)


In [28]:
x_1 = tf.constant([[5, 3, 6, 6, 4, 6],], dtype = tf.float32)
x_2 = tf.constant([[7], [5], [3]], dtype = tf.float32)
print(x_1.shape)
print(x_2.shape)
print(tf.add(x_1,x_2))

(1, 6)
(3, 1)
tf.Tensor(
[[12. 10. 13. 13. 11. 13.]
 [10.  8. 11. 11.  9. 11.]
 [ 8.  6.  9.  9.  7.  9.]], shape=(3, 6), dtype=float32)


In [39]:
x_argmax = tf.constant([[2, 20, 30, 3, 6],
                        [3, 11, 16, 1, 8],
                        [14, 45, 23, 5, 27]],)
print(x_argmax.shape)
print(tf.math.argmax(x_argmax, 0)) #find max in columns #0 means in other dimention (means column not row)
print(tf.math.argmin(x_argmax, 0))
print("*****************************************************************************")
print(tf.math.argmax(x_argmax, 1))#find max in rows
print(tf.math.argmin(x_argmax, 1))

(3, 5)
tf.Tensor([2 2 0 2 2], shape=(5,), dtype=int64)
tf.Tensor([0 1 1 1 0], shape=(5,), dtype=int64)
*****************************************************************************
tf.Tensor([2 2 1], shape=(3,), dtype=int64)
tf.Tensor([0 3 3], shape=(3,), dtype=int64)


In [33]:
x_argmax = tf.constant([2, 20, 30, 3, 6])
print(tf.math.argmax(x_argmax)) #index of max value
print(tf.math.argmin(x_argmax)) #index of min value

tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(0, shape=(), dtype=int64)


In [34]:
x_argmax = tf.constant([200, 120, 130, 3, 6])
print(tf.math.argmax(x_argmax))
print(tf.math.argmin(x_argmax))

tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)


In [35]:
x_argmax = tf.constant([200, 120, 130, 300, 6])
print(tf.math.argmax(x_argmax))
print(tf.math.argmin(x_argmax))

tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)


In [40]:
x = tf.constant([[2, 2], [3, 3]])
y = tf.constant([[3, 0], [1, 4]])
tf.pow(x,y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 8,  1],
       [ 3, 81]], dtype=int32)>

In [41]:
tf.pow(tf.constant(2),tf.constant(3))

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [49]:
tensor_two_d= tf.constant([
    [1, 2, 0],
    [3, 5, -1],
    [1, 5, 6],
    [2, 3, 8],
])
#axis=0 row       axis=1 column
print(tensor_two_d.shape)
print(tf.math.reduce_sum(tensor_two_d, axis=None, keepdims=False, name=None)) #sum all elements
print(tf.math.reduce_max(tensor_two_d, axis=None, keepdims=False, name=None)) #just show max
print(tf.math.reduce_sum(tensor_two_d, axis=0, keepdims=False, name=None)) #sum each column
print(tf.math.reduce_sum(tensor_two_d, axis=1, keepdims=False, name=None)) #sum each row
print(tf.math.reduce_max(tensor_two_d, axis=1, keepdims=False, name=None))
print(tf.math.reduce_mean(tensor_two_d, axis=1, keepdims=False, name=None))
print(tf.math.reduce_mean(tensor_two_d, axis=0, keepdims=False, name=None))

(4, 3)
tf.Tensor(35, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor([ 7 15 13], shape=(3,), dtype=int32)
tf.Tensor([ 3  7 12 13], shape=(4,), dtype=int32)
tf.Tensor([2 5 6 8], shape=(4,), dtype=int32)
tf.Tensor([1 2 4 4], shape=(4,), dtype=int32)
tf.Tensor([1 3 3], shape=(3,), dtype=int32)


In [52]:
tensor_two_d= tf.constant([
    [1, 2, 0],
    [3, 5, -1],
    [1, 5, 6],
    [2, 3, 8],
], dtype= tf.float16)
print(tf.math.reduce_mean(tensor_two_d, axis=0, keepdims=False, name=None))
print(tf.math.reduce_std(tensor_two_d, axis=0, keepdims=False, name=None))
print(tf.math.reduce_std(tensor_two_d, axis=0, keepdims=True, name=None))

tf.Tensor([1.75 3.75 3.25], shape=(3,), dtype=float16)
tf.Tensor([0.829 1.299 3.832], shape=(3,), dtype=float16)
tf.Tensor([[0.829 1.299 3.832]], shape=(1, 3), dtype=float16)


In [53]:
tf.math.top_k(tensor_two_d, k=1)

TopKV2(values=<tf.Tensor: shape=(4, 1), dtype=float16, numpy=
array([[2.],
       [5.],
       [6.],
       [8.]], dtype=float16)>, indices=<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[1],
       [1],
       [2],
       [2]], dtype=int32)>)

In [54]:
tf.math.top_k(tensor_two_d, k=2)

TopKV2(values=<tf.Tensor: shape=(4, 2), dtype=float16, numpy=
array([[2., 1.],
       [5., 3.],
       [6., 5.],
       [8., 3.]], dtype=float16)>, indices=<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[1, 0],
       [1, 0],
       [2, 1],
       [2, 1]], dtype=int32)>)

In [57]:
x_1 = tf.constant([
    [1, 2, 0],
    [3, 5, -1]
])

x_2 = tf.constant([
    [1, 2, 0],
    [3, 5, -1],
    [4, 5, 6]
])
print(x_1.shape, x_2.shape)

#zarb
tf.linalg.matmul(
    x_1, x_2, transpose_a=False, transpose_b=False, adjoint_a=False, adjoint_b=False, a_is_sparse=False, b_is_sparse=False, output_type=None, name=None
)

(2, 3) (3, 3)


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[  7,  12,  -2],
       [ 14,  26, -11]], dtype=int32)>

In [58]:
x_1 = tf.constant([
    [1, 2, 0],
    [3, 5, -1]
])

x_2 = tf.constant([
    [1, 2, 0, 2],
    [3, 5, -1, 2],
    [4, 5, 6, 0]
])
print(x_1.shape, x_2.shape)

#zarb
tf.linalg.matmul(
    x_1, x_2, transpose_a=False, transpose_b=False, adjoint_a=False, adjoint_b=False, a_is_sparse=False, b_is_sparse=False, output_type=None, name=None
)

(2, 3) (3, 4)


<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[  7,  12,  -2,   6],
       [ 14,  26, -11,  16]], dtype=int32)>

In [59]:
x_1 = tf.constant([
    [1, 2, 0],
])

x_2 = tf.constant([
    [1, 2, 0, 2],
    [3, 5, -1, 2],
    [4, 5, 6, 0]
])
print(x_1.shape, x_2.shape)

#zarb
tf.linalg.matmul(
    x_1, x_2, transpose_a=False, transpose_b=False, adjoint_a=False, adjoint_b=False, a_is_sparse=False, b_is_sparse=False, output_type=None, name=None
)

(1, 3) (3, 4)


<tf.Tensor: shape=(1, 4), dtype=int32, numpy=array([[ 7, 12, -2,  6]], dtype=int32)>

In [62]:
print(x_1@x_2)
x_1@x_2

tf.Tensor([[ 7 12 -2  6]], shape=(1, 4), dtype=int32)


<tf.Tensor: shape=(1, 4), dtype=int32, numpy=array([[ 7, 12, -2,  6]], dtype=int32)>